### PR TITLE
Update Windows installation README.md

### LINKED ISSUE #44: Improve instruction to build ssimulacra2
I don't have the technology literacy to understand the instruction and what I need to do. The instruction provided was not sufficient for me and I don't wish for anyone to go through the pain.

I managed to compile and run it after many trial runs. If anyone want to check out how I did this, here's the step. It's mostly for Windows, sorry for anyone who's looking to do this in Linux, I failed to do it on Ubuntu

1. Enter this link [http://www.vapoursynth.com/doc/installation.html#linux-installation,](https://www.vapoursynth.com/doc/installation.html#windows-installation)
2. Follow the prerequisites to download the required python
3. Enter the [VapourSynth installer](https://github.com/vapoursynth/vapoursynth/releases) link and download the .exe file
4. Then download the latest release-x86_64-cachedir-cwd.zip from https://github.com/AkarinVS/L-SMASH-Works/releases/tag/vA.3j
5. Run the exe file, don't modify or change any setting if you are not familar with it
6. After Vapoursynth is installed, find the path, typically C:\Users\<username>\AppData\Local\Programs\VapourSynth\sdk\lib64 (REPLACE THE username WITH YOUR!!)
7. decompress the .zip folder, and copy and paste the libvslsmashsource.dll to C:\Users\<username>\AppData\Local\Programs\VapourSynth\plugins
8. (I only attempted this on Powershell), There are different command shell to use. Use the command below according to what shell you're using. DON'T FORGET TO REPLACE USERNAME OR PATH FROM STEP 6.
- Powershell: $env:LIB="C:\Users\<username>\vapoursynth-portable\sdk\lib64;$env:LIB"
- CMD: set LIB=C:\Users\<username>\vapoursynth-portable\sdk\lib64;%LIB%
- Bash: export LIB="C:/Users/<username>/vapoursynth-portable/sdk/lib64:$LIB"

9. If you have rust installed, attempt "cargo install ssimulacra2_rs" on your cli.
10. If it fail because it require Visual Studio or Visual studio tool, download them. I downloaded Visual
10_1. You can download on https://visualstudio.microsoft.com/downloads/ Find the "Tools for Visual Studio" bar and download the "Remote Tools for Visual Studio 2022". Run it
10_2. Make sure Desktop Development with C++ is checked, leave the optional check installation alone and download it.
10_3. Retry step 8 again after you reboot your PC.
11. Run ssimulacra2_rs -h to check if it's running.
12. You're done!

### PR DESCRIPTION
**Pull request by Ves02**
Fix #44

### CODE REVIEW

**Comment by FreezyLemon** [comment]
Hm.. VS has both user-only and System-wide installation support. Can you add that to the VS installation step?

I'll try this on a VM and give you some more feedback sometime next week

**Comment by Ves02** [comment]
> Hm.. VS has both user-only and System-wide installation support. Can you add that to the VS installation step?

Is that relevant?

I specifically have user download the Visual C++ Build Tools to compile programs into an exe file. Rust requires a linker, libraries and Windows API import libraries. If the user doesn't have VS in the first place which come with the Visual C++ Build Tools, then VS would just be a huge bloat for them since there's high change they never use VS.

**Comment by FreezyLemon** [comment]
Sorry, I meant VapourSynth not Visual Studio. If a user installs VapourSynth system-wide, the paths are C:\VapourSynth and not appdata or something like that

**Comment by Ves02** [comment]
I missed that step! Thank for the catch.

**Review by FreezyLemon — APPROVED** [review]
Thanks for taking the time to improve the documentation.

**Comment by FreezyLemon** [comment]
Oh, this is interesting. @shssoichiro the `build` CI action is required to merge PRs but ignores `*.md` and `*.yml` changes. Since this PR only edits the README, it doesn't activate the workflow and can't be merged...

**Comment by shssoichiro** [comment]
Huh, that's interesting and kind of annoying. I can bypass the checks, I'll definitely have to look into a fix for that later.

**Pull request merged**
